apiVersion: v1
kind: Pod
metadata:
  name: configmap-ex1-pod
  labels:
    app: configmap-ex1-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: CM_EX1_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap-ex1
              key: appName
        - name: CM_EX1_APP_VER
          valueFrom:
            configMapKeyRef:
              name: configmap-ex1
              key: appVersion  
        - name: CM_EX1_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: configmap-ex1
              key: logLevel  
  restartPolicy: Never
