apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  selector:
    matchLabels:
      app: nginx-pod
  replicas: 3
  template:  
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: nginx-http-port
          containerPort: 80
          protocol: TCP    
          
          