apiVersion: v1
kind: Pod
metadata:
  name: secret1-pod
spec:
  containers:
  - name: mycontainer
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: secret1-opaque
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret1-opaque
            key: password
  restartPolicy: Never