apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1-hostfile-pvc
spec:
  storageClassName: vol1-hostfile-demo 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
     