apiVersion: v1
kind: Pod
metadata:
  name: vol1-emptydir-pod
spec:
  volumes:
  - name: workdir
    emptyDir: {}
  dnsPolicy: Default
  # These containers are run during pod initialization
  initContainers:
  - name: install
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "echo 'Hello empty volume demo' > /work-dir/index.html" ]  
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"    
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html

