kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1-hostfile-pv
  labels:
    type: local
spec:
  storageClassName: pv-demo 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/persistent-volume"