apiVersion: v1
kind: Pod
metadata:
  name: vol1-hostfile-pod
spec:
  volumes:
    - name: workdir
      persistentVolumeClaim:
       claimName: vol1-hostfile-pvc 
  containers:
  - name: install
    image: k8s.gcr.io/busybox
    # run in look to avoid exiting
    command: 
      - /bin/sh
      - "-c"
      - "tail -f /dev/null"
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"    
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

        
        
