apiVersion: v1
kind: Pod
metadata:
  name: vol1-hostfile-pod
spec:
  volumes:
    - name: vol1-hostfile-mount
      persistentVolumeClaim:
       claimName: vol1-hostfile-pvc 
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: myvolumes-container
    volumeMounts:
      - mountPath: "/pvdemo-path"
        name: vol1-hostfile-mount
