apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1-pv-hostfile
  labels:
    type: local-pv
spec:
  storageClassName: pv-demo 
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/local-pv"
