apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1-hostfile-pv
  labels:
    type: local-pv
spec:
  storageClassName: vol1-hostfile-demo 
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/local-pv"
